### ISSUE TITLE
Unneccessary permissions

### ISSUE THREAD

**Issue by est31** [lsubel/amam-cordova#2]
Is it possible to remove the unneccessary permissions from the [AndroidManifest.xml](https://github.com/lsubel/amam-cordova/blob/b3ca90804d704b36bfeceffd2d2de0d7bf65f9f6/platforms/android/AndroidManifest.xml)? Having the app without internet access would be cool.

See also : https://cordova.apache.org/docs/en/2.0.0/guide/getting-started/android/ they suggest to remove unneeded permissions as well.

**Comment by lsubel** [comment]
Unfortunately it is not possible. These permissions are all necessary to start the app. However, if you want to develop a native Android application with no permissions, feel free to use the content of this repository! :-)
