### ISSUE TITLE
Fix versioncode

### ISSUE THREAD

**Issue by ghost** [lsubel/amam-cordova#6]
In 765343b38c780149b010691b879f506c32139d0a you changed the versioncode format from 10303 to 133. Android's versioncodes are integer values that get compared to check if a release is actually an update. Since 133 or 134 is lower than 10303, the latest version is not considered an update.

**Comment by lsubel** [comment]
Thanks to the hint. :-)
The version code change was introduced after updating the config.xml file. The version code was updated in 1cbfcab6a3d5cad97688761c4b5ab02bfda97a50.
